version: '3.7'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; flask run --host 0.0.0.0'
    volumes:
      - .:/docker-flask-postgres
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: "postgres:11"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
